"ui.background" = "light-black"
"ui.text" = "white"
"ui.menu" = { fg = "black", bg = "light-gray" }
"ui.menu.selected" = { modifiers = ["reversed"] }
"ui.popup" = { modifiers = ["reversed"] }
"ui.linenr" = "gray"
"ui.linenr.selected" = { fg = "white", bg = "black", modifiers = ["bold"] }
"ui.selection" = { fg = "black", bg = "blue" }
"ui.selection.primary" = { fg = "white", bg = "blue" }
"comment" = { fg = "gray" }
"ui.statusline" = { fg = "white", bg = "black" }
"ui.cursor" = { fg = "white", modifiers = ["reversed"] }
"variable" = "red"
"constant.numeric" = "yellow"
"constant" = "yellow"
"attributes" = "yellow"
"type" = "yellow"
"ui.cursor.match" = { fg = "yellow", modifiers = ["underlined"] }
"string"  = "green"
"variable.other.member" = "green"
"constant.character.escape" = "cyan"
"function" = "blue"
"constructor" = "blue"
"special" = "blue"
"keyword" = "magenta"
"label" = "magenta"
"namespace" = "magenta"
"ui.help" = { fg = "white", bg = "black" }

"ui.virtual.indent-guide" = "black"
"ui.virtual.indent-guide.selected" = { bg = "black"}

"markup.heading" = "blue"
"markup.list" = "red"
"markup.bold" = { fg = "yellow", modifiers = ["bold"] }
"markup.italic" = { fg = "magenta", modifiers = ["italic"] }
"markup.link.url" = { fg = "yellow", modifiers = ["underlined"] }
"markup.link.text" = "red"
"markup.quote" = "cyan"
"markup.raw" = "green"

"diff.plus" = "green"
"diff.delta" = "yellow"
"diff.minus" = "red"

"diagnostic" = { modifiers = ["underlined"] }
"ui.gutter" = { bg = "black" }
"info" = "blue"
"hint" = "gray"
"debug" = "gray"
"warning" = "yellow"
"error" = "red"


[palette]
black     = "#1A1A1A"
blue      = "#5c78ff"
cyan      = "#5ac8ff"
green     = "#905aff"
magenta   = "#5ea2ff"
red       = "#ba5aff"
white     = "#ffffff"
yellow    = "#657b83"
gray      = "#171717"

light-black   = "#666666"
light-blue    = "#2b4fff"
light-cyan    = "#28b9ff"
light-green   = "#7129ff"
light-magenta = "#2883ff"
light-red     = "#a52aff"
light-white   = "#f1f1f1"
light-yellow  = "#3d2aff"
light-gray    = "#1d1d1d"